### ISSUE TITLE
Error while trying to read *.raw file

### ISSUE THREAD

**Issue by GodloveD** [Nesvilab/MSFragger#122]
### versions
msfraggger v3.1.1
philosopher v3.3.12

### platform
```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux cn0850 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```
### description
I'm trying to complete the tutorial [here](https://github.com/Nesvilab/philosopher/wiki/Simple-Data-Analysis).  Executing the following command in step 3 produces the following error:
```
$ java -Xmx32g -jar $MSFRAGGER_JAR closed_fragger.params \ 
   20190202_QExHFX2_RSLC8_PST_HeLa_10ng_1ulLoop_muPAC_1hr_15k_7.raw
[...snip]
        of length 48: 5458
        of length 49: 2938
        of length 50: 1736
In total 5756177 peptides.
Generated 9227949 modified peptides.
Number of peptides with more than 5000 modification patterns: 0
Selected fragment index width 0.10 Da.
378983008 fragments to be searched in 1 slices (5.65 GB total)
Operating on slice 1 of 1:
        Fragment index slice generated in 12.58 s
        001. 20190202_QExHFX2_RSLC8_PST_HeLa_10ng_1ulLoop_muPAC_1hr_15k_7.raw java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
        at com.dmtavt.batmass.io.ms.api.ISvcMsFramesIndexedGrpc$ISvcMsFramesIndexedBlockingStub.getFramesByIndex(ISvcMsFramesIndexedGrpc.java:282)
        at umich.ms.fileio.filetypes.thermo.ThermoRawFile.parseRange(ThermoRawFile.java:536)
        at umich.ms.fileio.filetypes.thermo.ThermoRawFile.parse(ThermoRawFile.java:575)
        at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:807)
        at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:791)
        at edu.umich.andykong.msfragger.b.a(Unknown Source)
        at edu.umich.andykong.msfragger.b.a(Unknown Source)
        at edu.umich.andykong.msfragger.E.a(Unknown Source)
        at edu.umich.andykong.msfragger.B.<init>(Unknown Source)
        at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
        at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
        ... 6 more
```
According to issue #41, this is is likely because I need to download the proper extensions to read `*.raw` files and place them in the `ext` subdirectory with the msfragger jar file.  But as you can see, I already have the correct files:
```
$ ls
closed_fragger.params            open_fragger.params
ext                              RawFileRdr_License_Agreement_RevA.pdf
glyco_params                     redist.txt
MSFragger-3.1.1.jar              TESTDATA
MSFragger-LICENSE-3RD-PARTY.txt  THIRD-PARTY-LICENSE-README.txt
MSFragger-LICENSE.pdf            version.txt
nonspecific_fragger.params

$ ls ext/bruker/
libtimsdata-2-7-0.so  THIRD-PARTY-LICENSE-README.txt  timsdata-2-7-0.lib
redist.txt            timsdata-2-7-0.dll
```
I've also added both the `bruker` and `thermo` subdirectories to the `$LD_LIBRARY_PATH` just in case that is needed, but it doesn't help.  Any suggestions are appreciated.  Thanks!

**Comment by fcyu** [comment]
Thanks for using our tools. 

First of all, did you install mono? Thermo's raw file reader needs it in Linux.

Second, I actually never tested Philosopher pipeline, and I am not sure if Philosopher pipeline works well with raw format. So, we need to check if your error is due to the Philosopher pipeline. Could you please try to run MSFragger in your console with a command like `java -Xmx32g -jar msfragger.jar fragger.params <your file>.raw`?

If the error is still there, you need to check if your system's firewall prevents the grpc from working because the error message is `Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason`

Best,

Fengchao

**Comment by GodloveD** [comment]
Thank you for the quick response @fcyu.  Good eye too.  You are right that I am running in an environment with a restrictive firewall.  I did not realize that would cause this error.  Converting the data from raw to mzML format has fixed the issue.

**Comment by fcyu** [comment]
You are welcome.
