### ISSUE TITLE
Error when Searching Specific Files

### ISSUE THREAD

**Issue by mamccabe** [Nesvilab/MSFragger#229]
Hello,

I have been processing a large dataset of raw files generated on a timsTOF Pro MS system. While most files search without issue using this pipeline, some specific files will not complete their searches regardless of the MSFragger version used. 

The searches crash immediately after "Main Search Done" dialog. I have attached the log file from one of the searches and pasted the error code below. Any insight into why I am getting this error would be greatly appreciated!

[log_2022-07-15_13-13-05.txt](https://github.com/Nesvilab/MSFragger/files/9124427/log_2022-07-15_13-13-05.txt)

Thanks,

Max

Traceback (most recent call last):
  File "C:\Users\HansenLab\Fragpipe\tools\msfragger_pep_split.py", line 630, in <module>
    main()
  File "C:\Users\HansenLab\Fragpipe\tools\msfragger_pep_split.py", line 618, in main
    write_combined_scores_histo()
  File "C:\Users\HansenLab\Fragpipe\tools\msfragger_pep_split.py", line 139, in write_combined_scores_histo
    scores_histos = [
  File "C:\Users\HansenLab\Fragpipe\tools\msfragger_pep_split.py", line 140, in <listcomp>
    sum(pd.read_csv(ee / (e.stem + '_scores_histogram.tsv'), dtype=np.uint64, header=None, sep='\t').values
  File "C:\Users\HansenLab\Fragpipe\tools\msfragger_pep_split.py", line 140, in <genexpr>
    sum(pd.read_csv(ee / (e.stem + '_scores_histogram.tsv'), dtype=np.uint64, header=None, sep='\t').values
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'split_peptide_index_tempdir\\0\\AA_DAorta_A1_HS_S3-B4_1_7957_scores_histogram.tsv'

**Comment by fcyu** [comment]
This error was from the split database. Guo Ci @guoci , can you take a look?

Thanks,

Fengchao

**Comment by guoci** [comment]
@mamccabe Can you show me the folder listing of `split_peptide_index_tempdir`?
It seems that some files are missing.
