### ISSUE TITLE
IonQuant Error

### ISSUE THREAD

**Issue by asaviola** [Nesvilab/MSFragger#231]
Hello, I am receiving the following error with all searches. Everything is updated. Thank you!
2022-07-20 15:35:39 [INFO] - Quantifying...
2022-07-20 15:35:39 [INFO] - Updating Philosopher's tables...
java.lang.NullPointerException: Something was wrong in update protein.tsv
	at s.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2022-07-20 15:35:40 [ERROR] - Something was wrong in update protein.tsv
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

[log_2022-07-20_15-35-40.txt](https://github.com/Nesvilab/MSFragger/files/9154674/log_2022-07-20_15-35-40.txt)
s

**Comment by fcyu** [comment]
Can you upgrade FragPipe to the latest version and try again?

Thanks,

Fengchao

**Comment by asaviola** [comment]
Hi Fengchao,

Thanks for your response. With upgraded FragPipe I can get fully tryptic searches to finish but when I change to cleavage to semtryptic it fails at the following step:
In total 95843752 peptides.
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at s.a(Unknown Source)
	at r.a(Unknown Source)
	at k.a(Unknown Source)
	at o.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
Process 'MSFragger' finished, exit code: 1
Process returned non-zero exit code, stopping
~~~~~~~~~~~~~~~~~~~~
Cancelling 165 remaining tasks


[log_2022-07-20_17-58-57.txt](https://github.com/Nesvilab/MSFragger/files/9160883/log_2022-07-20_17-58-57.txt)

**Comment by fcyu** [comment]
There is not enough memory. You have several variable modifications:
```
variable_mod_01 = 15.994900 M 3
variable_mod_02 = 42.010600 [^ 1
variable_mod_03 = 79.966330 STY 3
variable_mod_04 = -17.026500 nQnC 1
variable_mod_11 = 0.984016 NQ 1
```

I think you can at lease remove deamidation, and probability -17.

Best,

Fengchao

**Comment by fcyu** [comment]
Yes. 1) Finding another computer with more memory; 2) increase `split database` in MSFragger tab (you need to have Python ready).

Best,

Fengchao

**Comment by asaviola** [comment]
Excellent, thank you.
