### ISSUE TITLE
FragPipe not working 

### ISSUE THREAD

**Issue by pankajdwid** [Nesvilab/MSFragger#272]
[log_2023-07-24_11-50-16.txt](https://github.com/Nesvilab/MSFragger/files/12147688/log_2023-07-24_11-50-16.txt)

**Comment by fcyu** [comment]
> [pool-1-thread-5] ERROR com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess - Did not get port information from server output within timeout.
[pool-11-thread-1] ERROR com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess - Error while scanning stream
java.lang.InterruptedException: sleep interrupted
	at java.base/java.lang.Thread.sleep(Native Method)
	at com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess.scanStreamForPattern(ThermoGrpcServerProcess.java:319)
	at com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess.lambda$start$7(ThermoGrpcServerProcess.java:261)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[pool-11-thread-1] ERROR com.dmtavt.batmass.io.thermo.ThermoGrpcServerProcess - Batmass-IO Thermo server (1.3.0.0)

MSFragger could not communicate with the Thermo library. Something, such as antivirus software, in your computer might block it. If you could not figure out the reason, please convert your files to mzML format: https://fragpipe.nesvilab.org/docs/tutorial_convert.html

Best,

Fengchao
