### ISSUE TITLE
Java-related error of MSFragger 3.8 and FragPipe20.0

### ISSUE THREAD

**Issue by jjnbdal** [Nesvilab/MSFragger#278]
[log_2023-08-31_15-39-29.txt](https://github.com/Nesvilab/MSFragger/files/12484293/log_2023-08-31_15-39-29.txt)

Dear Support,

We installed MSfragger3.8 and Fragpipe20.0 to run BSA digest (mzML format, converted from Bruker .d file via MSConvert). The process worked fine on my laptop, but when installing the same on a desktop PC, we got the error below. (we also attached the log file).

F:\BSA\msfragger_out\fragpipe-bsa100ng_RE8_01_32150.pepXML-temp
Exception in thread "main" java.nio.file.FileSystemException: F:\BSA\msfragger_out\fragpipe-bsa100ng_RE8_01_32150.pepXML-temp: The process cannot access the file because it is being used by another process.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.base/java.nio.file.Files.delete(Unknown Source)
	at com.github.chhh.utils.FileDelete$1.postVisitDirectory(FileDelete.java:72)
	at com.github.chhh.utils.FileDelete$1.postVisitDirectory(FileDelete.java:49)
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source)
	at com.github.chhh.utils.FileDelete.deleteFileOrFolder(FileDelete.java:49)
	at com.github.chhh.utils.FileDelete.main(FileDelete.java:45)
Process 'PeptideProphet: Delete temp' finished, exit code: 1
Process returned non-zero exit code, stopping
15:39:28 WARN : Attempt #1 to delete file we need to delete is being used by another process: F:\BSA\msfragger_out\fragpipe-bsa100ng_RE8_01_32150.pepXML-temp

~~~~~~~~~~~~~~~~~~~~
Cancelling 8 remaining tasks

Can you please help suggest us what to do to fix it?

Best Regards,
Jaran

**Comment by fcyu** [comment]
Could you share the whole log file?

Also, it is NOT recommend converting .d to mzML format. FragPipe natively support .d

Best,

Fengchao
