### ISSUE TITLE
Exception when searching

### ISSUE THREAD

**Issue by shawn-peng** [Nesvilab/MSFragger#46]
I'm running searches with .mgf files. For one file it went successfully, but for another file I got the following exception,
	ecoli-total-2-3_RC3_01_455_AnashkL5.mgf 971ms [progress: 256/56829 (0.45%) - 2560.00 spectra/s]Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
	at n.b(Unknown Source)
	at MSFragger.main(Unknown Source)
	... 5 more
Could anyone help me with this problem? Thanks!

**Comment by fcyu** [comment]
Thanks for your interest in MSFragger. Could you please upload the MGF file, fragger.params, and fasta file to [https://umich.app.box.com/upload-widget/view/5w9w1bgdexm0u73gvoadc9s28jqohuuw/93093019419?fr=%3A%3FDECF4E%3A%40%3FDlUE%3AE%3D6l%24F3%3E%3AETa_u%3A%3D6WDXTa_E%40Ta_%3ADDF60ceU%3ADs6D4C%3AAE%3A%40%3Fu%3A6%3D5%249%40H%3Fl_U%3ADt%3E2%3A%3D%236BF%3AC65l_](https://umich.app.box.com/upload-widget/view/5w9w1bgdexm0u73gvoadc9s28jqohuuw/93093019419?fr=%3A%3FDECF4E%3A%40%3FDlUE%3AE%3D6l%24F3%3E%3AETa_u%3A%3D6WDXTa_E%40Ta_%3ADDF60ceU%3ADs6D4C%3AAE%3A%40%3Fu%3A6%3D5%249%40H%3Fl_U%3ADt%3E2%3A%3D%236BF%3AC65l_)?

Thanks,

Fengchao

**Comment by shawn-peng** [comment]
I uploaded those files. I forgot to change the path of the database. This just came to mind after I uploaded them. Please make a modification. Thanks!

**Comment by fcyu** [comment]
Thanks. Unfortunately, I cannot reproduce your error. Following is the log:
```
java -Xmx32g -jar MSFragger-2.2.jar msfragger_conf_decoy ecoli-total-2-3_RC3_01_455_AnashkL5.mgf
MSFragger version MSFragger-2.2
Batmass-IO version 1.17.1
(c) University of Michigan
RawFileReader reading tool. Copyright (c) 2016 by Thermo Fisher Scientific, Inc. All rights reserved.
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_231, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 26 GB memory

Checking E:\issue_46\ecoli-total-2-3_RC3_01_455_AnashkL5.mgf...

***********************************FIRST SEARCH************************************
Parameters:
num_threads = 8
database_name = uniprot-proteome_UP000000625.fasta
decoy_prefix = rev_
precursor_mass_lower = -25.0
precursor_mass_upper = 25.0
precursor_mass_units = 1
precursor_true_tolerance = 25.0
precursor_true_units = 1
fragment_mass_tolerance = 15.0
fragment_mass_units = 1
calibrate_mass = 2
write_calibrated_mgf = true
isotope_error = 0
mass_offsets = 0
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
search_enzyme_name = nonspecific
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 0
allowed_missed_cleavage = 1
clip_nTerm_M = true
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_mod = 3
max_variable_mods_combinations = 5000
output_file_extension = tsv
output_format = tsv
output_report_topN = 1
output_max_expect = 5.0E9
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 8
digest_max_length = 15
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 2
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 150
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.01
intensity_transform = 0
remove_precursor_peak = 0
remove_precursor_range = -1.5,1.5
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
variable_mod_02 = 42.01060 [^
add_A_alanine = 0.000000
add_B_user_amino_acid = 0.000000
add_C_cysteine = 57.021464
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_D_aspartic_acid = 0.000000
add_E_glutamic_acid = 0.000000
add_F_phenylalanine = 0.000000
add_G_glycine = 0.000000
add_H_histidine = 0.000000
add_I_isoleucine = 0.000000
add_J_user_amino_acid = 0.000000
add_K_lysine = 0.000000
add_L_leucine = 0.000000
add_M_methionine = 0.000000
add_N_asparagine = 0.000000
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
add_O_user_amino_acid = 0.000000
add_P_proline = 0.000000
add_Q_glutamine = 0.000000
add_R_arginine = 0.000000
add_S_serine = 0.000000
add_T_threonine = 0.000000
add_U_user_amino_acid = 0.000000
add_V_valine = 0.000000
add_W_tryptophan = 0.000000
add_X_user_amino_acid = 0.000000
add_Y_tyrosine = 0.000000
add_Z_user_amino_acid = 0.000000
Number of unique peptides
	of length 8: 1300045
	of length 9: 1298354
	of length 10: 1295750
	of length 11: 1292710
	of length 12: 1289386
	of length 13: 1285866
	of length 14: 1282204
	of length 15: 1278444
In total 10322759 peptides.
Generated 10391803 modified peptides.
Selected fragment tolerance 0.08 Da and maximum fragment slice size of 20.44 GB.
217962812 fragments to be searched in 1 slices (3.25 GB total)
Operating on slice 1 of 1: 
	001. ecoli-total-2-3_RC3_01_455_AnashkL5.mgf 8.5 s [progress: 56829/56829 (100.00%) - 9034.82 spectra/s] - completed 6.3 s
***************************FIRST SEARCH DONE IN 0.608 MIN**************************

*********************************MASS CALIBRATION**********************************
-----|---------------|---------------|---------------|---------------
     |  MS1   (Old)  |  MS1   (New)  |  MS2   (Old)  |  MS2   (New)  
-----|---------------|---------------|---------------|---------------
 Run |  Median  MAD  |  Median  MAD  |  Median  MAD  |  Median  MAD  
 001 |  -0.08   2.38 |   0.08   2.21 |  -0.33   5.81 |  -0.17   5.14  
-----|---------------|---------------|---------------|---------------
Finding the optimal parameters:
-------|-------|-------|-------
  MS2  |   10  |   15  |   20  
-------|-------|-------|-------
 Count |  18001|  21025|  23037
-------|-------|-------|-------
-------|-------|-------
 Peaks | 150_1 | 100_1 
-------|-------|-------
 Count |  23037|  20654
-------|-------|-------
-------|-------
 Int.  |    1  
-------|-------
 Count |  23097
-------|-------
-------|-------
 Rm P. |    1  
-------|-------
 Count |  23385
-------|-------
New fragment_mass_tolerance = 20 PPM
New use_topN_peaks = 150
New minimum_ratio = 0.010000
New intensity_transform = 1
New remove_precursor_peak = 1
**************************MASS CALIBRATION DONE IN 1.322 MIN***********************

************************************MAIN SEARCH************************************
Parameters:
num_threads = 8
database_name = uniprot-proteome_UP000000625.fasta
decoy_prefix = rev_
precursor_mass_lower = -25.0
precursor_mass_upper = 25.0
precursor_mass_units = 1
precursor_true_tolerance = 25.0
precursor_true_units = 1
fragment_mass_tolerance = 20.0
fragment_mass_units = 1
calibrate_mass = 2
write_calibrated_mgf = true
isotope_error = 0/1
mass_offsets = 0
precursor_mass_mode = SELECTED
localize_delta_mass = false
delta_mass_exclude_ranges = (-1.5,3.5)
fragment_ion_series = b,y
search_enzyme_name = nonspecific
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 0
allowed_missed_cleavage = 1
clip_nTerm_M = true
allow_multiple_variable_mods_on_residue = false
max_variable_mods_per_mod = 3
max_variable_mods_combinations = 5000
output_file_extension = tsv
output_format = tsv
output_report_topN = 1
output_max_expect = 5.0E9
report_alternative_proteins = false
override_charge = false
precursor_charge_low = 1
precursor_charge_high = 4
digest_min_length = 7
digest_max_length = 25
digest_mass_range_low = 500.0
digest_mass_range_high = 5000.0
max_fragment_charge = 2
track_zero_topN = 0
zero_bin_accept_expect = 0.0
zero_bin_mult_expect = 1.0
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 150
minIonsScoring = 2
min_matched_fragments = 4
minimum_ratio = 0.01
intensity_transform = 1
remove_precursor_peak = 1
remove_precursor_range = -1.5,1.5
clear_mz_range_low = 0.0
clear_mz_range_high = 0.0
excluded_scan_list_file = 
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
add_A_alanine = 0.000000
add_B_user_amino_acid = 0.000000
add_C_cysteine = 57.021464
add_Cterm_peptide = 0.0
add_Cterm_protein = 0.0
add_D_aspartic_acid = 0.000000
add_E_glutamic_acid = 0.000000
add_F_phenylalanine = 0.000000
add_G_glycine = 0.000000
add_H_histidine = 0.000000
add_I_isoleucine = 0.000000
add_J_user_amino_acid = 0.000000
add_K_lysine = 0.000000
add_L_leucine = 0.000000
add_M_methionine = 0.000000
add_N_asparagine = 0.000000
add_Nterm_peptide = 0.0
add_Nterm_protein = 0.0
add_O_user_amino_acid = 0.000000
add_P_proline = 0.000000
add_Q_glutamine = 0.000000
add_R_arginine = 0.000000
add_S_serine = 0.000000
add_T_threonine = 0.000000
add_U_user_amino_acid = 0.000000
add_V_valine = 0.000000
add_W_tryptophan = 0.000000
add_X_user_amino_acid = 0.000000
add_Y_tyrosine = 0.000000
add_Z_user_amino_acid = 0.000000
Number of unique peptides
	of length 7: 1296944
	of length 8: 1300045
	of length 9: 1298354
	of length 10: 1295750
	of length 11: 1292710
	of length 12: 1289386
	of length 13: 1285866
	of length 14: 1282204
	of length 15: 1278444
	of length 16: 1274610
	of length 17: 1270714
	of length 18: 1266768
	of length 19: 1262792
	of length 20: 1258775
	of length 21: 1254725
	of length 22: 1250655
	of length 23: 1246572
	of length 24: 1242475
	of length 25: 1238377
In total 24186166 peptides.
Generated 37179104 modified peptides.
Selected fragment tolerance 0.10 Da and maximum fragment slice size of 20.20 GB.
1167513438 fragments to be searched in 1 slices (17.40 GB total)
Operating on slice 1 of 1: 
	001. ecoli-total-2-3_RC3_01_455_AnashkL5.mzBIN_calibrated 1.3 s [progress: 56313/56313 (100.00%) - 3853.89 spectra/s] - completed 14.6 s
***************************MAIN SEARCH DONE IN 1.150 MIN***************************

*******************************TOTAL TIME 3.080 MIN********************************
```

However, your fasta file doesn't have decoy proteins. You need it and make sure that the value of `decoy_prefix` matches the prefix of your decoy proteins.

Thanks,

Fengchao

**Comment by shawn-peng** [comment]
Hi Fengchao,
From the output you posted, I noticed that I was using a very old version of fragger. Now I have successfully done the search. Closing the issue. Thanks a lot for your help!

Best,
Yisu
