### ISSUE TITLE
java exception: NoClassDefFoundError & ClassNotFoundException

### ISSUE THREAD

**Issue by skeffington** [Nesvilab/MSFragger#91]
Hi,

I was trying to use MSFragger, but got the error below. My input file derrives from a thermo RAW file converted to mzXML with msconvert. 

I was running MSFragger like this

```
java -Xmx28G -jar ~/Tools/MSFragger-20171106/MSFragger-20171106.jar par.params Fos_A.mzXML
```

And here's the error:

```
MSFragger version MSFragger-20171106
(c) University of Michigan

Peptide index read in 253ms
Selected fragment tolerance 10.00 Da and maximum fragment slice size of 22025.25MB
728742484 fragments to be searched in 1 slices (5.43GB total)
Operating on slice 1 of 1: 8887ms
	Fos_A.mzXML Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: umich/ms/fileio/filetypes/LCMSDataSource
	at n.c(Unknown Source)
	at n.a(Unknown Source)
	at MSFragger.main(Unknown Source)
	... 5 more
Caused by: java.lang.ClassNotFoundException: umich.ms.fileio.filetypes.LCMSDataSource
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

Any clues as to how to solve this would be much appreciated!
Alastair

**Comment by fcyu** [comment]
You need to upgrade your MSFragger from here https://msfragger.arsci.com/upgrader/
